name: CI

on:
  schedule:
    - cron:  '10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Post webhook test
      run: curl -X POST -H "Content-Type: application/json" -d '{"value1":"1つ目"}' ${{ secrets.WEBHOOK_URL }}
